<?php

namespace Database\Seeders;

use App\Models\Answer;
use App\Models\Certificate;
use App\Models\Country;
use App\Models\Language;
use App\Models\Level;
use App\Models\Question;
use App\Models\Session;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $countries=['Afghanistan','Afghanistan','Albania','Algeria','Angola','Argentina','Armenia','Australia','Austria','Bahrain','Bangladesh','Belarus','Belgium','Bhutan','Bolivia','Bosnia'.'Herzegovina','Botswana','Brazil','Bulgaria','Cambodia','Cameroon','Canada','Chile','China','Colombia','Costa Rica','Croatia','Cuba','Cyprus','Czech Republic','Denmark','Ecuador','Egypt','Estonia','Ethiopia','Fiji','Finland','France','Germany','Ghana','Greece','Greenland','Guinea','Guyana','Haiti','Honduras','Hong Kong','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Italy','Japan','Jersey','Jordan','Kazakhstan','Kenya','Kuwait','Kyrgyzstan','Lebanon','Liberia','Libya','Lithuania','Luxembourg','Macedonia','Madagascar','Malaysia','Maldives','Mali','Mauritius','Mexico','Monaco','Mongolia','Morocco','Namibia','Nepal','Netherlands','New Zealand','Nigeria','North Korea','Norway','Oman','Pakistan','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Rwanda','Saudi Arabia','Serbia','Singapore','Slovakia','Slovenia','South Africa','South Korea','Spain','Sri Lanka','Sudan','Sweden','Switzerland','Syria','Taiwan','Tajikistan','Tanzania','Thailand','Tunisia','Turkey','Turkmenistan','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States','Uruguay','Uzbekistan','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe'];
        foreach ($countries as $key => $value) {
            Country::create(['country'=>$value]);
        }
        $users=[0=>['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibrahimelabdellaoui43@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>11,'xp'=>'530.00','image'=>'1661085489.jpg'],
        1=>['name'=>'Oussama TAOUATI','email'=>'oussamataouati@gmail.com','password'=>Hash::make('Oss@m@2000'),'level'=>9,'xp'=>'440.00'],
        2=>['name'=>'Ikram MOKANNA','email'=>'mokannaikram@gmail.com','password'=>Hash::make('Ikr@m1997'),'level'=>9,'xp'=>'420.00'],
        3=>['name'=>'Ahmad OULAD AOUID','email'=>'Ouladaouida@gmail.com','password'=>Hash::make('Ahm@d2002'),'level'=>11,'xp'=>'500.00'],
        4=>['name'=>'Zakaria BEN AZAIZ','email'=>'zakariabenazaizsuport@gmail.com','password'=>Hash::make('Z@k@r@i0284'),'level'=>9,'xp'=>'430.00'],
        5=>['name'=>'Ziyad BENHDOUBA','email'=>'benhdouba.ziyad@gmail.com','password'=>Hash::make('Ziy@d2002'),'level'=>9,'xp'=>'430.00'],
        6=>['name'=>'Mohammed BAIAOU','email'=>'Its.mohammedb1@gmail.com','password'=>Hash::make('Moh@mmed2000'),'level'=>10,'xp'=>'450.00'],
        7=>['name'=>'Mohamed CHENTOUF','email'=>'mchentouf05@gmail.com','password'=>Hash::make('Moh@med2000'),'level'=>5,'xp'=>'210.00'],
        8=>['name'=>'Mostafa EL CHAHMOUTI','email'=>'mostafaelchahmouti@outlook.com','password'=>Hash::make('Most@f@1998'),'level'=>9,'xp'=>'420.00'],
        9=>['name'=>'Abdehafid HAJI','email'=>'abdehafidhaji0@gmail.com','password'=>Hash::make('Abdeh@fid2000'),'level'=>11,'xp'=>'510.00'],
        10=>['name'=>'Ashraf AGDOUR','email'=>'ash3raaad@gmail.com','password'=>Hash::make('Ashr@f2000'),'level'=>9,'xp'=>'420.00'],
        11=>['name'=>'Aymen BEN AZAIZ','email'=>'Moroccopz@gmail.com','password'=>Hash::make('Aymen@2000'),'level'=>10,'xp'=>'480.00'],
        12=>['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibrahimelabdellaoui2001@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>11,'xp'=>'510.00'],
        13=>['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibrahimikmkn@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>11,'xp'=>'500.00'],
        14=>['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibrahimelabde@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>11,'xp'=>'520.00'],
        15=>['name'=>'Ahmad AFAKIR','email'=>'ahmadafakir23@gmail.com','password'=>Hash::make('Ahm@d1946'),'level'=>2,'xp'=>'070.00'],
        16=>['name'=>'Self EDUCATION','email'=>'selfeducation1622@gmail.com','password'=>Hash::make('Self@2022'),'level'=>99,'xp'=>'4920.00','image'=>'1661085184.png'],
        17=>['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibraelabde@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>7,'xp'=>'300.00'],
    ];
        foreach ($users as $key => $value) {
            User::create($value);
        }
        Language::create([
            'language_name'=>'C',
        ]);
        $levels=[0=>['level_name'=>'Level 1','language_id'=>1],
        1=>['level_name'=>'Level 2','language_id'=>1],
        2=>['level_name'=>'Level 3','language_id'=>1],
    ];
    foreach ($levels as $key => $value) {
        Level::create($value);
    }
        $certificates=[0=>['user_id'=>1,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>33],
        1=>['user_id'=>2,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 08m 38s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        2=>['user_id'=>3,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 21m 54s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        3=>['user_id'=>4,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 01m 29s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        4=>['user_id'=>5,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 15m 32s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        5=>['user_id'=>6,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 14m 18s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        6=>['user_id'=>7,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 10m 24s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        7=>['user_id'=>8,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>67],
        8=>['user_id'=>9,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 27m 44s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        9=>['user_id'=>10,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'00h 53m 32s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        10=>['user_id'=>11,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 20m 24s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        11=>['user_id'=>12,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 12m 31s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        12=>['user_id'=>13,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 02m 38s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        13=>['user_id'=>14,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 04m 38s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        14=>['user_id'=>15,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'01h 01m 54s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        15=>['user_id'=>16,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>33],
        16=>['user_id'=>17,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>100,'time_passed'=>'00h 18m 00s','certificate_validate'=>true,'date_validate'=>date("d M, Y")],
        17=>['user_id'=>18,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>67],
    ];
    foreach ($certificates as $key => $value) {
        Certificate::create($value);
    }
    // User::create(['name'=>'Ibrahim ELABDELLAOUI','email'=>'ibrahimelabdellaoui43@gmail.com','password'=>Hash::make('Ibr@2001'),'level'=>11,'xp'=>'530.00','image'=>'1661085489.jpg']);
    // Certificate::create(['user_id'=>1,'language_id'=>1,'certificate_id'=>\Ramsey\Uuid\Uuid::uuid4()->toString(),'language_progress'=>67]);
    // Session::create(['user_id'=>1,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 15m 15s']);
    // Session::create(['user_id'=>1,'level_id'=>2,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 20m 30s']);
    // Session::create(['user_id'=>1,'level_id'=>3]);
    $sessions=[0=>['user_id'=>1,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 15m 15s'],
                1=>['user_id'=>1,'level_id'=>2,'session_validate'=>false],
                // 2=>['user_id'=>1,'level_id'=>3,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 25m 14s'],
                3=>['user_id'=>2,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 19m 37s'],
                4=>['user_id'=>2,'level_id'=>2,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 21m 47s'],
                5=>['user_id'=>2,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 27m 14s'],
                6=>['user_id'=>3,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 23m 51s'],
                7=>['user_id'=>3,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 26m 49s'],
                8=>['user_id'=>3,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 31m 14s'],
                3=>['user_id'=>4,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 16m 26s'],
                4=>['user_id'=>4,'level_id'=>2,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 21m 49s'],
                5=>['user_id'=>4,'level_id'=>3,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 23m 14s'],
                6=>['user_id'=>5,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 21m 31s'],
                7=>['user_id'=>5,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 26m 43s'],
                8=>['user_id'=>5,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 27m 18s'],
                9=>['user_id'=>6,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 22m 37s'],
                10=>['user_id'=>6,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 25m 13s'],
                11=>['user_id'=>6,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 26m 28s'],
                12=>['user_id'=>7,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 19m 24s'],
                13=>['user_id'=>7,'level_id'=>2,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 23m 19s'],
                14=>['user_id'=>7,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 27m 41s'],
                15=>['user_id'=>8,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 28m 14s'],
                16=>['user_id'=>8,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 31m 49s'],
                17=>['user_id'=>8,'level_id'=>3],
                18=>['user_id'=>9,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 26m 14s'],
                19=>['user_id'=>9,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 29m 49s'],
                20=>['user_id'=>9,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 31m 41s'],
                21=>['user_id'=>10,'level_id'=>1,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 17m 33s'],
                22=>['user_id'=>10,'level_id'=>2,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 18m 55s'],
                23=>['user_id'=>10,'level_id'=>3,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 17m 04s'],
                24=>['user_id'=>11,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 25m 24s'],
                25=>['user_id'=>11,'level_id'=>2,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 26m 19s'],
                26=>['user_id'=>11,'level_id'=>3,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 28m 41s'],
                27=>['user_id'=>12,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 23m 31s'],
                28=>['user_id'=>12,'level_id'=>2,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 24m 19s'],
                29=>['user_id'=>12,'level_id'=>3,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 22m 41s'],
                30=>['user_id'=>13,'level_id'=>1,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 18m 31s'],
                31=>['user_id'=>13,'level_id'=>2,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 21m 26s'],
                32=>['user_id'=>13,'level_id'=>3,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 23m 41s'],
                33=>['user_id'=>14,'level_id'=>1,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 19m 31s'],
                34=>['user_id'=>14,'level_id'=>2,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 22m 26s'],
                35=>['user_id'=>14,'level_id'=>3,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 23m 41s'],
                36=>['user_id'=>15,'level_id'=>1,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 17m 31s'],
                37=>['user_id'=>15,'level_id'=>2,'session_validate'=>true,'session_progress'=>9,'session_time_passed'=>'00h 21m 26s'],
                38=>['user_id'=>15,'level_id'=>3,'session_validate'=>true,'session_progress'=>8,'session_time_passed'=>'00h 23m 41s'],
                39=>['user_id'=>16,'level_id'=>1,'session_validate'=>true,'session_progress'=>7,'session_time_passed'=>'00h 31m 31s'],
                40=>['user_id'=>16,'level_id'=>2],
                41=>['user_id'=>17,'level_id'=>1,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 05m 00s'],
                42=>['user_id'=>17,'level_id'=>2,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 06m 00s'],
                43=>['user_id'=>17,'level_id'=>3,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 07m 00s'],
                44=>['user_id'=>18,'level_id'=>1,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 15m 37s'],
                45=>['user_id'=>18,'level_id'=>2,'session_validate'=>true,'session_progress'=>10,'session_time_passed'=>'00h 16m 01s'],
                46=>['user_id'=>18,'level_id'=>3],
        ];
        foreach ($sessions as $key => $value) {
            Session::create($value);
        }

        $questions=[0=>['level_id'=>1,'question_text'=>'Which of the following are valid data types in c ?','title'=>'Data Types','image'=>'','type'=>'check'],
                    1=>['level_id'=>1,'question_text'=>'Constant variable PI.','title'=>'Constants','image'=>'','type'=>'check'],
                    2=>['level_id'=>1,'question_text'=>'Constant variable PI.','title'=>'Constants','image'=>'','type'=>'check'],
                    3=>['level_id'=>1,'question_text'=>'Fill in the blanks to declare a constant variable PI of type float.','title'=>'Constants','image'=>'','type'=>'check'],
                    4=>['level_id'=>1,'question_text'=>'Outside in the blanks to declare a constant variable PI of type float','title'=>'Constants','image'=>'','type'=>'check'],
                    5=>['level_id'=>1,'question_text'=>'Fill in the blanks to output "Hello Word!" to the screen:','title'=>'Basic','image'=>'','type'=>'check'],
                    6=>['level_id'=>1,'question_text'=>'Scanf variable c character ','title'=>'Basic','image'=>'','type'=>'check'],
                    7=>['level_id'=>1,'question_text'=>'Scanf variable c character ','title'=>'Basic','image'=>'char.png','type'=>'result'],
                    8=>['level_id'=>1,'question_text'=>'Declare variable s varchar number de character 10','title'=>'Declaration','image'=>'varchar.png','type'=>'result'],
                    9=>['level_id'=>1,'question_text'=>'Scanf two variables varchar s and s1 ','title'=>'Basic','image'=>'','type'=>'check'],
                    10=>['level_id'=>1,'question_text'=>'Scanf variable s varchar which contains 10 letters. ','title'=>'Basic','image'=>'','type'=>'check'],
                    11=>['level_id'=>1,'question_text'=>'Scanf variable a int ','title'=>'Declaration','image'=>'int.png','type'=>'result'],
                    12=>['level_id'=>1,'question_text'=>'Scanf variable b float ','title'=>'Declaration','image'=>'float.png','type'=>'result'],
                    13=>['level_id'=>1,'question_text'=>'Scanf two variables a int,b float ','title'=>'Basic','image'=>'int_float.png','type'=>'result'],
                    14=>['level_id'=>1,'question_text'=>'Declare two variables a integer number,b float number ','title'=>'Declaration','image'=>'','type'=>'check'],
                    15=>['level_id'=>1,'question_text'=>'Declare variable c character ','title'=>'Declaration','image'=>'char_d.png','type'=>'result'],
                    16=>['level_id'=>1,'question_text'=>'Print string "a=" plus value the variable a ','title'=>'Affiche','image'=>'','type'=>'check'],
                    17=>['level_id'=>1,'question_text'=>'Arrange the following correctly.','title'=>'Syntax','image'=>'','type'=>'order'],
                    18=>['level_id'=>1,'question_text'=>'Arrange the following correctly.','title'=>'Syntax','image'=>'','type'=>'order'],
                    19=>['level_id'=>1,'question_text'=>'Arrange the following correctly.','title'=>'Syntax','image'=>'','type'=>'order'],
                    20=>['level_id'=>1,'question_text'=>'Arrange the following correctly.','title'=>'Syntax','image'=>'','type'=>'order'],
                    21=>['level_id'=>1,'question_text'=>'Arrange the following correctly in order to change the values of a=7 ,b=2','title'=>'Syntax','image'=>'','type'=>'order'],
                    22=>['level_id'=>1,'question_text'=>'Print value the variable s varchar','title'=>'Affiche','image'=>'','type'=>'check'],
                    23=>['level_id'=>1,'question_text'=>'Fill in the blanks to output "Hello Word!" to the screen:','title'=>'Basic','image'=>'img_5.png','type'=>'result'],
                    24=>['level_id'=>1,'question_text'=>'Declare constant variable PI fill in the blanks ?','title'=>'Declaration','image'=>'const.png','type'=>'result'],
                    25=>['level_id'=>1,'question_text'=>'Declare constant variable PI no fill in the blanks ?','title'=>'Declaration','image'=>'define.png','type'=>'result'],
                    26=>['level_id'=>1,'question_text'=>'What is the value of the result variable?','title'=>'Operators','image'=>'result_1.png','type'=>'result'],
                    27=>['level_id'=>1,'question_text'=>'What is the value of the result variable?','title'=>'Operators','image'=>'result_2.png','type'=>'result'],
                    28=>['level_id'=>1,'question_text'=>'What is the value of the result variable?','title'=>'Operators','image'=>'result_3.png','type'=>'result'],
                    29=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_5.png','type'=>'result'],
                    30=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_6.png','type'=>'result'],
                    31=>['level_id'=>1,'question_text'=>'New line before b ?','title'=>'Formatting Output','image'=>'result_8.png','type'=>'result'],
                    32=>['level_id'=>1,'question_text'=>'Horizontal before b ?','title'=>'Formatting Output','image'=>'result_8.png','type'=>'result'],
                    33=>['level_id'=>1,'question_text'=>'Backslash before b ?','title'=>'Formatting Output','image'=>'result_8.png','type'=>'result'],
                    34=>['level_id'=>1,'question_text'=>'Backspace before b ?','title'=>'Formatting Output','image'=>'result_8.png','type'=>'result'],
                    35=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_7.png','type'=>'result'],
                    36=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_9.png','type'=>'result'],
                    37=>['level_id'=>1,'question_text'=>'Type in the missing operator to add the value of b to a.','title'=>'Operators','image'=>'result_4.png','type'=>'result'],
                    38=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_10.png','type'=>'result'],
                    39=>['level_id'=>1,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Operators','image'=>'result_11.png','type'=>'result'],
                    40=>['level_id'=>3,'question_text'=>'Convert the variable varchar s="2001" to variable int a','title'=>'Type Conversion','image'=>'','type'=>'check'],
                    41=>['level_id'=>1,'question_text'=>'Convert the variable int a=5 to variable float b','title'=>'Type Conversion','image'=>'','type'=>'check'],
                    42=>['level_id'=>1,'question_text'=>'Convert the variable float b=5.5 to variable int a','title'=>'Type Conversion','image'=>'','type'=>'check'],
                    43=>['level_id'=>2,'question_text'=>'Fill in the blanks to compare the variables in order to print "Hello World!" .','title'=>'Conditionals','image'=>'condition_1.png','type'=>'result'],
                    44=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Conditionals','image'=>'condition_2.png','type'=>'result'],
                    45=>['level_id'=>2,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Conditionals','image'=>'condition_3.png','type'=>'result'],
                    46=>['level_id'=>2,'question_text'=>'What is the value final of variable a to the screen?','title'=>'Conditionals','image'=>'condition_4.png','type'=>'result'],
                    47=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Conditionals','image'=>'condition_5.png','type'=>'result'],
                    48=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Conditionals','image'=>'condition_6.png','type'=>'result'],
                    49=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Switch','image'=>'switch_1.png','type'=>'result'],
                    50=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Switch','image'=>'switch_2.png','type'=>'result'],
                    51=>['level_id'=>2,'question_text'=>'Result that will appear in the screen.','title'=>'Conditionals','image'=>'condition_7.png','type'=>'result'],
                    52=>['level_id'=>2,'question_text'=>'Fill in the blanks to print "Roman" if n is either\'x\' or \'X\':','title'=>'Conditionals','image'=>'condition_8.png','type'=>'result'],
                    53=>['level_id'=>2,'question_text'=>'Which is the correct operator for equality testing?','title'=>'Conditionals','image'=>'','type'=>'check'],
                    54=>['level_id'=>2,'question_text'=>'Which choice shows the correct syntax for the switch statement?','title'=>'Switch','image'=>'','type'=>'check'],
                    55=>['level_id'=>2,'question_text'=>'Which choice shows the correct syntax for the while loop?" .','title'=>'The while Loop','image'=>'','type'=>'check'],
                    56=>['level_id'=>2,'question_text'=>'Which choice shows the correct syntax for the do while loop?" .','title'=>'The do while Loop','image'=>'','type'=>'check'],
                    57=>['level_id'=>2,'question_text'=>'Which choice shows the correct syntax for the for loop?" .','title'=>'The for Loop','image'=>'','type'=>'check'],
                    58=>['level_id'=>2,'question_text'=>'Arrange the following correctly.','title'=>'Conditionals','image'=>'','type'=>'order'],
                    59=>['level_id'=>2,'question_text'=>'Arrange the following correctly in order to int i=5.','title'=>'Switch','image'=>'','type'=>'order'],
                    60=>['level_id'=>2,'question_text'=>'Arrange the following codes with appropriate in order to print "Hello" 5 times.','title'=>'The while Loop','image'=>'','type'=>'order'],
                    61=>['level_id'=>2,'question_text'=>'Arrange the following codes with appropriate in order to print "Hello" 5 times (i integer equal 5).','title'=>'The do while Loop','image'=>'','type'=>'order'],
                    62=>['level_id'=>2,'question_text'=>'Arrange the following codes with appropriate in order to print multiplication table from 1 to 10 (i and n numbers integers).','title'=>'The for Loop','image'=>'','type'=>'order'],
                    63=>['level_id'=>2,'question_text'=>'Fill in the blanks with appropriate in order to print "Hello" 5 times?','title'=>'The while Loop','image'=>'while_1.png','type'=>'result'],
                    64=>['level_id'=>2,'question_text'=>'What is the value final of variable n to the screen?','title'=>'The while Loop','image'=>'while_2.png','type'=>'result'],
                    65=>['level_id'=>2,'question_text'=>'What is the value final of variable n to the screen?','title'=>'The do while Loop','image'=>'do_while_2.png','type'=>'result'],
                    66=>['level_id'=>2,'question_text'=>'Fill in the blanks with appropriate in order to print "Hello" 5 times?','title'=>'The do while Loop','image'=>'do_while_1.png','type'=>'result'],
                    67=>['level_id'=>2,'question_text'=>'What is the value final of variable n to the screen?','title'=>'The for Loop','image'=>'for_1.png','type'=>'result'],
                    68=>['level_id'=>2,'question_text'=>'Fill in the blanks with appropriate in order to print "Hello" 5 times?','title'=>'The for Loop','image'=>'for_2.png','type'=>'result'],
                    69=>['level_id'=>2,'question_text'=>'How many times has "Hello" appeared on the screen?','title'=>'Statements','image'=>'statement_1.png','type'=>'result'],
                    70=>['level_id'=>2,'question_text'=>'How many times has "Hello" appeared on the screen?','title'=>'Statements','image'=>'statement_2.png','type'=>'result'],
                    71=>['level_id'=>2,'question_text'=>'What is the value final of variable i ?','title'=>'Statements','image'=>'statement_3.png','type'=>'result'],
                    72=>['level_id'=>3,'question_text'=>'What is the first value of array t ?','title'=>'Arrays','image'=>'array_1.png','type'=>'result'],
                    73=>['level_id'=>3,'question_text'=>'What is the last value of array t ?','title'=>'Arrays','image'=>'array_1.png','type'=>'result'],
                    74=>['level_id'=>3,'question_text'=>'What is the first index of array t ?','title'=>'Arrays','image'=>'array_1.png','type'=>'result'],
                    75=>['level_id'=>3,'question_text'=>'What is the last index of array t ?','title'=>'Arrays','image'=>'array_1.png','type'=>'result'],
                    76=>['level_id'=>3,'question_text'=>'What is the value final of variable sum to the screen?','title'=>'Two-Dimensional Arrays','image'=>'array_2.png','type'=>'result'],
                    77=>['level_id'=>3,'question_text'=>'How many elements can the following array t hold ?','title'=>'Two-Dimensional Arrays','image'=>'array_2.png','type'=>'result'],
                    78=>['level_id'=>3,'question_text'=>'Convert the variable varchar s="207.14" to variable float a','title'=>'Type Conversion','image'=>'','type'=>'check'],
                    79=>['level_id'=>3,'question_text'=>'What is the value of variable t[1][2] ?','title'=>'Two-Dimensional Arrays','image'=>'array_2.png','type'=>'result'],
                    80=>['level_id'=>3,'question_text'=>'Result that will appear in the screen.','title'=>'Arrays','image'=>'array_3.png','type'=>'result'],
                    81=>['level_id'=>3,'question_text'=>'Result that will appear in the screen.','title'=>'Arrays','image'=>'array_4.png','type'=>'result'],
                    82=>['level_id'=>3,'question_text'=>'Result that will appear in the screen.','title'=>'Arrays','image'=>'array_5.png','type'=>'result'],
                    83=>['level_id'=>3,'question_text'=>'Fill in the blanks to make the correct code.','title'=>'Arrays','image'=>'array_6.png','type'=>'result'],
                    84=>['level_id'=>3,'question_text'=>'Fill in the blanks to make the correct code.','title'=>'Strings','image'=>'string_1.png','type'=>'result'],
                    85=>['level_id'=>3,'question_text'=>'Result that will appear in the screen.','title'=>'Strings','image'=>'string_2.png','type'=>'result'],
                    86=>['level_id'=>3,'question_text'=>'Result that will appear in the screen.','title'=>'Strings','image'=>'string_3.png','type'=>'result'],
                    87=>['level_id'=>3,'question_text'=>'Declare array arr Integer the size 10.','title'=>'Arrays','image'=>'','type'=>'check'],
                    88=>['level_id'=>3,'question_text'=>'What result of strcmp("Ibrahim","ELABDELLAOUI"):','title'=>'Strings','image'=>'','type'=>'check'],
                    89=>['level_id'=>3,'question_text'=>'What result of strcmp("A","a"):','title'=>'Strings','image'=>'','type'=>'check'],
                    90=>['level_id'=>3,'question_text'=>'What result of strlen("Ibrahim"):','title'=>'Strings','image'=>'','type'=>'check'],
                    91=>['level_id'=>3,'question_text'=>'Which true for pointers?','title'=>'Pointers','image'=>'','type'=>'check'],
                    92=>['level_id'=>3,'question_text'=>'What is the output of the following code?','title'=>'Pointers','image'=>'pointer_1.png','type'=>'result'],
                    93=>['level_id'=>3,'question_text'=>'Arrange the following codes.','title'=>'Pointers','image'=>'','type'=>'order'],
                    94=>['level_id'=>3,'question_text'=>'What is the output of the following code?','title'=>'Pointers','image'=>'pointer_2.png','type'=>'result'],
                    ];
        foreach ($questions as $key => $value) {
            Question::create($value);
        }
        $answers=[0=>['question_id'=>1,'answer_text'=>'boolean ,char ,int ,double .','order'=>''],
                    1=>['question_id'=>1,'answer_text'=>'double ,char ,string ,int .','order'=>''],
                    2=>['question_id'=>1,'answer_text'=>'char ,double ,float ,int .','answer_validate'=>true,'order'=>''],
                    3=>['question_id'=>1,'answer_text'=>'var ,double ,int ,char .','order'=>''],
                    4=>['question_id'=>2,'answer_text'=>'#define PI=3.14','order'=>''],
                    5=>['question_id'=>2,'answer_text'=>'let PI 3.14','order'=>''],
                    6=>['question_id'=>2,'answer_text'=>'final PI=3.14','order'=>''],
                    7=>['question_id'=>2,'answer_text'=>'#define PI 3.14','answer_validate'=>true,'order'=>''],
                    8=>['question_id'=>3,'answer_text'=>'const PI=3.14;','order'=>''],
                    9=>['question_id'=>3,'answer_text'=>'let PI 3.14;','order'=>''],
                    10=>['question_id'=>3,'answer_text'=>'const float PI=3.14;','answer_validate'=>true,'order'=>''],
                    11=>['question_id'=>3,'answer_text'=>'#define PI=3.14','order'=>''],
                    12=>['question_id'=>4,'answer_text'=>'const PI=3.14','order'=>''],
                    13=>['question_id'=>4,'answer_text'=>'let PI 3.14;','order'=>''],
                    14=>['question_id'=>4,'answer_text'=>'const float PI=3.14;','answer_validate'=>true,'order'=>''],
                    15=>['question_id'=>4,'answer_text'=>'#define PI 3.14','order'=>''],
                    16=>['question_id'=>5,'answer_text'=>'const PI=3.14','order'=>''],
                    17=>['question_id'=>5,'answer_text'=>'let PI 3.14','order'=>''],
                    18=>['question_id'=>5,'answer_text'=>'const float PI=3.14','order'=>''],
                    19=>['question_id'=>5,'answer_text'=>'#define PI 3.14','answer_validate'=>true,'order'=>''],
                    20=>['question_id'=>6,'answer_text'=>'printf("Hello World!");','answer_validate'=>true,'order'=>''],
                    21=>['question_id'=>6,'answer_text'=>'echo"Hello World!";','order'=>''],
                    22=>['question_id'=>6,'answer_text'=>'System.Out.print("Hello world!");','order'=>''],
                    23=>['question_id'=>6,'answer_text'=>'console.log("Hello World!");','order'=>''],
                    24=>['question_id'=>7,'answer_text'=>'c=gets();','order'=>''],
                    25=>['question_id'=>7,'answer_text'=>'scanf("c",&c);','order'=>''],
                    26=>['question_id'=>7,'answer_text'=>'c=getchar();','answer_validate'=>true,'order'=>''],
                    27=>['question_id'=>7,'answer_text'=>'scanf("%c",c);','order'=>''],
                    28=>['question_id'=>8,'answer_text'=>'c=getchar()','answer_validate'=>true,'order'=>''],
                    29=>['question_id'=>8,'answer_text'=>'scanf("%c",&c)','answer_validate'=>true,'order'=>''],
                    30=>['question_id'=>9,'answer_text'=>'char s[10]','answer_validate'=>true,'order'=>''],
                    31=>['question_id'=>10,'answer_text'=>'scanf("%s %s",&s &s1);','order'=>''],
                    32=>['question_id'=>10,'answer_text'=>'scanf("%s,%s",&s1,&s);','order'=>''],
                    33=>['question_id'=>11,'answer_text'=>'scanf("%s",&s);','answer_validate'=>true,'order'=>''],
                    34=>['question_id'=>11,'answer_text'=>'scanf("s",&s);','order'=>''],
                    35=>['question_id'=>11,'answer_text'=>'s=getchar();','order'=>''],
                    36=>['question_id'=>11,'answer_text'=>'scanf("%c",s);','order'=>''],
                    37=>['question_id'=>12,'answer_text'=>'scanf("%d",&a)','answer_validate'=>true,'order'=>''],
                    38=>['question_id'=>13,'answer_text'=>'scanf("%f",&b)','answer_validate'=>true,'order'=>''],
                    39=>['question_id'=>14,'answer_text'=>'scanf("%d %f",&a,&b)','answer_validate'=>true,'order'=>''],
                    40=>['question_id'=>14,'answer_text'=>'scanf("%f %d",&b,&a)','answer_validate'=>true,'order'=>''],
                    41=>['question_id'=>15,'answer_text'=>'var a,b;','order'=>''],
                    42=>['question_id'=>15,'answer_text'=>'int a;float b;','answer_validate'=>true,'order'=>''],
                    43=>['question_id'=>15,'answer_text'=>'$a=0;$b=0.0;','order'=>''],
                    44=>['question_id'=>15,'answer_text'=>'let a,b;','order'=>''],
                    45=>['question_id'=>16,'answer_text'=>'char','answer_validate'=>true,'order'=>''],
                    46=>['question_id'=>17,'answer_text'=>'printf("a=%d",a);','answer_validate'=>true,'order'=>''],
                    47=>['question_id'=>17,'answer_text'=>'printf("a=a");','order'=>''],
                    48=>['question_id'=>17,'answer_text'=>'echo "a=".$a;','order'=>''],
                    49=>['question_id'=>17,'answer_text'=>'printf("a=%s",a);','order'=>''],
                    50=>['question_id'=>18,'answer_text'=>'int main(int argc, char** argv) {','order'=>1],
                    51=>['question_id'=>18,'answer_text'=>'return 0;}','order'=>3],
                    52=>['question_id'=>18,'answer_text'=>'printf("Contant PI=%.2f",PI);','order'=>2],
                    53=>['question_id'=>18,'answer_text'=>'#define PI 3.14','order'=>0],
                    54=>['question_id'=>19,'answer_text'=>'int main(int argc, char** argv) {','order'=>0],
                    55=>['question_id'=>19,'answer_text'=>'return 0;}','order'=>3],
                    56=>['question_id'=>19,'answer_text'=>'putchar(c);','order'=>2],
                    57=>['question_id'=>19,'answer_text'=>'char c=getchar();','order'=>1],
                    58=>['question_id'=>20,'answer_text'=>'int main(int argc, char** argv) {','order'=>0],
                    59=>['question_id'=>20,'answer_text'=>'printf("Welcome %s",Name);','order'=>2],
                    60=>['question_id'=>20,'answer_text'=>'return 0;}','order'=>3],
                    61=>['question_id'=>20,'answer_text'=>'char Name[30];Name=gets();','order'=>1],
                    62=>['question_id'=>21,'answer_text'=>'char c;','order'=>0],
                    63=>['question_id'=>21,'answer_text'=>'printf("First character of your name :\t%s",c);','order'=>1],
                    64=>['question_id'=>21,'answer_text'=>'return 0;}','order'=>3],
                    65=>['question_id'=>21,'answer_text'=>'scanf("%c",&Name);','order'=>2],
                    66=>['question_id'=>22,'answer_text'=>'int a=2,b=7,c;','order'=>0],
                    67=>['question_id'=>22,'answer_text'=>'a=b;','order'=>2],
                    68=>['question_id'=>22,'answer_text'=>'b=c','order'=>3],
                    69=>['question_id'=>22,'answer_text'=>'c=a;','order'=>1],
                    70=>['question_id'=>23,'answer_text'=>'puts(s);','answer_validate'=>true,'order'=>''],
                    71=>['question_id'=>23,'answer_text'=>'printf(s);','order'=>''],
                    72=>['question_id'=>23,'answer_text'=>'echo s;','order'=>''],
                    73=>['question_id'=>23,'answer_text'=>'printf("%d",s);','order'=>''],
                    74=>['question_id'=>10,'answer_text'=>'scanf("%s %s",s,s1);','answer_validate'=>true,'order'=>''],
                    75=>['question_id'=>10,'answer_text'=>'scanf("%s s",&s s1);','order'=>''],
                    76=>['question_id'=>24,'answer_text'=>'printf','answer_validate'=>true,'order'=>''],
                    77=>['question_id'=>25,'answer_text'=>'const','answer_validate'=>true,'order'=>''],
                    78=>['question_id'=>26,'answer_text'=>'define','answer_validate'=>true,'order'=>''],
                    79=>['question_id'=>27,'answer_text'=>'2','answer_validate'=>true,'order'=>''],
                    80=>['question_id'=>28,'answer_text'=>'7','answer_validate'=>true,'order'=>''],
                    81=>['question_id'=>29,'answer_text'=>'2','answer_validate'=>true,'order'=>''],
                    82=>['question_id'=>30,'answer_text'=>'50','answer_validate'=>true,'order'=>''],
                    83=>['question_id'=>31,'answer_text'=>'50','answer_validate'=>true,'order'=>''],
                    84=>['question_id'=>32,'answer_text'=>'n','answer_validate'=>true,'order'=>''],
                    85=>['question_id'=>33,'answer_text'=>'t','answer_validate'=>true,'order'=>''],
                    86=>['question_id'=>34,'answer_text'=>'\\','answer_validate'=>true,'order'=>''],
                    87=>['question_id'=>35,'answer_text'=>'b','answer_validate'=>true,'order'=>''],
                    88=>['question_id'=>36,'answer_text'=>'49','answer_validate'=>true,'order'=>''],
                    89=>['question_id'=>37,'answer_text'=>'16','answer_validate'=>true,'order'=>''],
                    90=>['question_id'=>38,'answer_text'=>'+=','answer_validate'=>true,'order'=>''],
                    91=>['question_id'=>39,'answer_text'=>'17','answer_validate'=>true,'order'=>''],
                    92=>['question_id'=>40,'answer_text'=>'4','answer_validate'=>true,'order'=>''],
                    93=>['question_id'=>41,'answer_text'=>'int a=(int)s;','order'=>''],
                    94=>['question_id'=>41,'answer_text'=>'int a=parseInt(s);','order'=>''],
                    95=>['question_id'=>41,'answer_text'=>'int a=atoi(s);','answer_validate'=>true,'order'=>''],
                    96=>['question_id'=>41,'answer_text'=>'int a=int s','order'=>''],
                    97=>['question_id'=>42,'answer_text'=>'float b=float a;','order'=>''],
                    98=>['question_id'=>42,'answer_text'=>'float b=parseFloat(a);','order'=>''],
                    99=>['question_id'=>42,'answer_text'=>'float b=(float)a;','answer_validate'=>true,'order'=>''],
                    100=>['question_id'=>42,'answer_text'=>'float b=double s','order'=>''],
                    101=>['question_id'=>43,'answer_text'=>'int a=(Integer)b;','order'=>''],
                    102=>['question_id'=>43,'answer_text'=>'int a=parseInt(b);','order'=>''],
                    103=>['question_id'=>43,'answer_text'=>'int a=(int)b;','answer_validate'=>true,'order'=>''],
                    104=>['question_id'=>43,'answer_text'=>'int a=int b','order'=>''],
                    105=>['question_id'=>44,'answer_text'=>'if','answer_validate'=>true,'order'=>''],
                    106=>['question_id'=>54,'answer_text'=>'==','answer_validate'=>true,'order'=>''],
                    107=>['question_id'=>54,'answer_text'=>'+=','order'=>''],
                    108=>['question_id'=>54,'answer_text'=>'<>','order'=>''],
                    109=>['question_id'=>54,'answer_text'=>'!=','order'=>''],
                    110=>['question_id'=>45,'answer_text'=>'a>b','answer_validate'=>true,'order'=>''],
                    111=>['question_id'=>46,'answer_text'=>'8','answer_validate'=>true,'order'=>''],
                    112=>['question_id'=>47,'answer_text'=>'9','answer_validate'=>true,'order'=>''],
                    113=>['question_id'=>48,'answer_text'=>'a equal b','answer_validate'=>true,'order'=>''],
                    114=>['question_id'=>49,'answer_text'=>'negative','answer_validate'=>true,'order'=>''],
                    115=>['question_id'=>55,'answer_text'=>'switch test;','order'=>''],
                    116=>['question_id'=>55,'answer_text'=>'switch (test) { }','answer_validate'=>true,'order'=>''],
                    117=>['question_id'=>55,'answer_text'=>'SWITCH test { }','order'=>''],
                    118=>['question_id'=>55,'answer_text'=>'while test','order'=>''],
                    119=>['question_id'=>50,'answer_text'=>'a prime number','answer_validate'=>true,'order'=>''],
                    120=>['question_id'=>51,'answer_text'=>'number','answer_validate'=>true,'order'=>''],
                    121=>['question_id'=>52,'answer_text'=>'b positive','answer_validate'=>true,'order'=>''],
                    122=>['question_id'=>53,'answer_text'=>'||','answer_validate'=>true,'order'=>''],
                    123=>['question_id'=>65,'answer_text'=>'5','answer_validate'=>true,'order'=>''],
                    124=>['question_id'=>64,'answer_text'=>'while','answer_validate'=>true,'order'=>''],
                    125=>['question_id'=>56,'answer_text'=>'while i<5 i++;','order'=>''],
                    126=>['question_id'=>56,'answer_text'=>'while (i<5) {i++; }','answer_validate'=>true,'order'=>''],
                    127=>['question_id'=>56,'answer_text'=>'While i<5 {i++; }','order'=>''],
                    128=>['question_id'=>56,'answer_text'=>'do while (i<5){i++;}','order'=>''],
                    129=>['question_id'=>57,'answer_text'=>'do while i<5 i++;','order'=>''],
                    130=>['question_id'=>57,'answer_text'=>'do(i<5) {i++; }while;','order'=>''],
                    131=>['question_id'=>57,'answer_text'=>'do{i++; }while(i<5);','answer_validate'=>true,'order'=>''],
                    132=>['question_id'=>57,'answer_text'=>'do while (i<5){i++;}','order'=>''],
                    133=>['question_id'=>58,'answer_text'=>'for i=0;i<5;i++ {}','order'=>''],
                    134=>['question_id'=>58,'answer_text'=>'for(i=0;i++;i<5){}','order'=>''],
                    135=>['question_id'=>58,'answer_text'=>'for(i=0,i<5,i++){}','order'=>''],
                    136=>['question_id'=>58,'answer_text'=>'for(i=0;i<5;i++){}','answer_validate'=>true,'order'=>''],
                    137=>['question_id'=>66,'answer_text'=>'10','answer_validate'=>true,'order'=>''],
                    138=>['question_id'=>67,'answer_text'=>'9','answer_validate'=>true,'order'=>''],
                    139=>['question_id'=>67,'answer_text'=>'10','answer_validate'=>true,'order'=>''],
                    140=>['question_id'=>68,'answer_text'=>'5','answer_validate'=>true,'order'=>''],
                    141=>['question_id'=>69,'answer_text'=>'for','answer_validate'=>true,'order'=>''],
                    142=>['question_id'=>59,'answer_text'=>'if( i > 0 )','order'=>0],
                    143=>['question_id'=>59,'answer_text'=>'else','order'=>2],
                    144=>['question_id'=>59,'answer_text'=>'printf("positive");','order'=>1],
                    145=>['question_id'=>59,'answer_text'=>'printf("negative");','order'=>3],
                    146=>['question_id'=>60,'answer_text'=>'switch ( i ){','order'=>1],
                    147=>['question_id'=>60,'answer_text'=>'case 5: printf("a prime number");','order'=>2],
                    148=>['question_id'=>60,'answer_text'=>'default: printf("number");}','order'=>3],
                    149=>['question_id'=>60,'answer_text'=>'int i=5;','order'=>0],
                    150=>['question_id'=>63,'answer_text'=>'for( n=1 ; n<11 ; n++ ){','order'=>0],
                    151=>['question_id'=>63,'answer_text'=>'printf("%d * %d = %d\n",n,i,n*i);','order'=>2],
                    152=>['question_id'=>63,'answer_text'=>'}','order'=>3],
                    153=>['question_id'=>63,'answer_text'=>'for( i=0 ; i<11 ; i++ )','order'=>1],
                    154=>['question_id'=>61,'answer_text'=>'while ( i<5 ){','order'=>1],
                    155=>['question_id'=>61,'answer_text'=>'printf("Hello\\n");','order'=>2],
                    156=>['question_id'=>61,'answer_text'=>'i++;}','order'=>3],
                    157=>['question_id'=>61,'answer_text'=>'int i=5;','order'=>0],
                    158=>['question_id'=>62,'answer_text'=>'do{','order'=>0],
                    159=>['question_id'=>62,'answer_text'=>'printf("Hello\\n");','order'=>1],
                    160=>['question_id'=>62,'answer_text'=>'}while(i<5)','order'=>3],
                    161=>['question_id'=>62,'answer_text'=>'i++;','order'=>2],
                    162=>['question_id'=>70,'answer_text'=>'4','answer_validate'=>true,'order'=>''],
                    163=>['question_id'=>71,'answer_text'=>'3','answer_validate'=>true,'order'=>''],
                    164=>['question_id'=>72,'answer_text'=>'10','answer_validate'=>true,'order'=>''],
                    165=>['question_id'=>73,'answer_text'=>'4','answer_validate'=>true,'order'=>''],
                    166=>['question_id'=>74,'answer_text'=>'1','answer_validate'=>true,'order'=>''],
                    167=>['question_id'=>75,'answer_text'=>'0','answer_validate'=>true,'order'=>''],
                    168=>['question_id'=>76,'answer_text'=>'4','answer_validate'=>true,'order'=>''],
                    169=>['question_id'=>77,'answer_text'=>'58','answer_validate'=>true,'order'=>''],
                    170=>['question_id'=>78,'answer_text'=>'6','answer_validate'=>true,'order'=>''],
                    171=>['question_id'=>79,'answer_text'=>'int a=(float)s;','order'=>''],
                    172=>['question_id'=>79,'answer_text'=>'int a=parseFloat(s);','order'=>''],
                    173=>['question_id'=>79,'answer_text'=>'int a=atof(s);','answer_validate'=>true,'order'=>''],
                    174=>['question_id'=>79,'answer_text'=>'int a=float s;','order'=>''],
                    175=>['question_id'=>80,'answer_text'=>'27','answer_validate'=>true,'order'=>''],
                    176=>['question_id'=>81,'answer_text'=>'1-2-3-4-5','answer_validate'=>true,'order'=>''],
                    177=>['question_id'=>82,'answer_text'=>'1-2-6','answer_validate'=>true,'order'=>''],
                    178=>['question_id'=>83,'answer_text'=>'3','answer_validate'=>true,'order'=>''],
                    179=>['question_id'=>84,'answer_text'=>'int','answer_validate'=>true,'order'=>''],
                    180=>['question_id'=>85,'answer_text'=>'string.h','answer_validate'=>true,'order'=>''],
                    181=>['question_id'=>86,'answer_text'=>'ElabdellaouiIbrahim','answer_validate'=>true,'order'=>''],
                    182=>['question_id'=>87,'answer_text'=>'-1','answer_validate'=>true,'order'=>''],
                    183=>['question_id'=>88,'answer_text'=>'int arr=[10]','order'=>''],
                    184=>['question_id'=>88,'answer_text'=>'$arr=[10];','order'=>''],
                    185=>['question_id'=>88,'answer_text'=>'int arr[10];','answer_validate'=>true,'order'=>''],
                    186=>['question_id'=>88,'answer_text'=>'int arr[]=10;','order'=>''],
                    187=>['question_id'=>89,'answer_text'=>'-1','order'=>''],
                    188=>['question_id'=>89,'answer_text'=>'true','order'=>''],
                    189=>['question_id'=>89,'answer_text'=>'1','answer_validate'=>true,'order'=>''],
                    190=>['question_id'=>89,'answer_text'=>'false','order'=>''],
                    191=>['question_id'=>90,'answer_text'=>'-1','answer_validate'=>true,'order'=>''],
                    192=>['question_id'=>90,'answer_text'=>'true','order'=>''],
                    193=>['question_id'=>90,'answer_text'=>'1','order'=>''],
                    194=>['question_id'=>90,'answer_text'=>'false','order'=>''],
                    195=>['question_id'=>91,'answer_text'=>'6','order'=>''],
                    196=>['question_id'=>91,'answer_text'=>'56','order'=>''],
                    197=>['question_id'=>91,'answer_text'=>'8','order'=>''],
                    198=>['question_id'=>91,'answer_text'=>'7','answer_validate'=>true,'order'=>''],
                    199=>['question_id'=>92,'answer_text'=>'Pointers are useless and make programmers lives a nightmare.','order'=>''],
                    200=>['question_id'=>92,'answer_text'=>'Pointers are storing the values of variables.','order'=>''],
                    201=>['question_id'=>92,'answer_text'=>'Pointers can be used in expressions just as any variable.','answer_validate'=>true,'order'=>''],
                    202=>['question_id'=>92,'answer_text'=>'Cannot place pointer on table.','order'=>''],
                    203=>['question_id'=>93,'answer_text'=>'33','answer_validate'=>true,'order'=>''],
                    204=>['question_id'=>94,'answer_text'=>'int *p=a;','order'=>1],
                    205=>['question_id'=>94,'answer_text'=>'int res =*(p+2);','order'=>2],
                    206=>['question_id'=>94,'answer_text'=>'printf("%d",res);','order'=>3],
                    207=>['question_id'=>94,'answer_text'=>'int a[]={22,33,44,55,66};','order'=>0],
                    208=>['question_id'=>95,'answer_text'=>'11','answer_validate'=>true,'order'=>''],
                ];
        foreach ($answers as $key => $value) {
            Answer::create($value);
        }
    }
}
